name: merge
services:
  cuda:
    stdin_open: true
    tty: true
    container_name: cuda
    volumes:
      - ./:/data
      - ./videos:/videos
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    image: nvidia/cuda:12.6.3-cudnn-devel-ubuntu24.04
    command: bash
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility